# Server plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: false
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: In
        values:
          - "true"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade:v1.24.2-k3s1@sha256:2559d791d948926d405e456749e8902a0e07fc8fe068421071d1e2dbd5a356f0
  channel: https://update.k3s.io/v1-release/channels/v1.24
---
# Agent plan
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: false
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: DoesNotExist
  prepare:
    args:
      - prepare
      - server-plan
    image: rancher/k3s-upgrade:v1.24.2-k3s1@sha256:2559d791d948926d405e456749e8902a0e07fc8fe068421071d1e2dbd5a356f0
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade:v1.24.2-k3s1@sha256:2559d791d948926d405e456749e8902a0e07fc8fe068421071d1e2dbd5a356f0
  channel: https://update.k3s.io/v1-release/channels/v1.24
